"""adjusted tables for first name and last name

Revision ID: 419ad3161880
Revises: 1479974f5ce1
Create Date: 2026-05-21 15:47:58.621883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '419ad3161880'
down_revision: Union[str, Sequence[str], None] = "1479974f5ce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistedtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti')
    )
    op.create_index(op.f('ix_blacklistedtokens_session_id'), 'blacklistedtokens', ['session_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_uid'), 'password_reset_tokens', ['uid'], unique=False)
    op.create_table('signup_links',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hospital_uid', sa.String(), nullable=False),
    sa.Column('department_uid', sa.String(), nullable=True),
    sa.Column('admin_type', postgresql.ENUM('SUPER_ADMIN', 'HOSPITAL_ADMIN', 'DEPARTMENT_ADMIN', name='admin_type'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_signup_links_token'), 'signup_links', ['token'], unique=True)
    op.create_index(op.f('ix_signup_links_uid'), 'signup_links', ['uid'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'HOSPITAL', 'PATIENT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('hospitals',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('full_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('ownership_type', sa.Enum('PRIVATE', 'GOVERNMENT', 'NGO', name='hospital_type'), nullable=False),
    sa.Column('status', sa.Enum('UNDER_REVIEW', 'APPROVED', 'REJECTED', name='hospital_status'), nullable=False),
    sa.Column('hospital_ceo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('average_rating', sa.NUMERIC(precision=2, scale=1), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('hospital_name'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_hospitals_user_uid'), 'hospitals', ['user_uid'], unique=False)
    op.create_table('messages',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('sender_uid', sa.UUID(), nullable=False),
    sa.Column('receiver_uid', sa.UUID(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_messages_receiver_uid'), 'messages', ['receiver_uid'], unique=False)
    op.create_index(op.f('ix_messages_sender_uid'), 'messages', ['sender_uid'], unique=False)
    op.create_index(op.f('ix_messages_uid'), 'messages', ['uid'], unique=False)
    op.create_table('notifications',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_notifications_uid'), 'notifications', ['uid'], unique=False)
    op.create_index(op.f('ix_notifications_user_uid'), 'notifications', ['user_uid'], unique=False)
    op.create_table('patients',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hospital_card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_of_residence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blood_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emergency_contact_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emergency_contact_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_patients_user_uid'), 'patients', ['user_uid'], unique=False)
    op.create_table('refreshtokens',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_refreshtokens_jti'), 'refreshtokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refreshtokens_session_id'), 'refreshtokens', ['session_id'], unique=True)
    op.create_index(op.f('ix_refreshtokens_uid'), 'refreshtokens', ['uid'], unique=False)
    op.create_index(op.f('ix_refreshtokens_user_uid'), 'refreshtokens', ['user_uid'], unique=False)
    op.create_table('departments',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('hospital_uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_uid'], ['hospitals.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_departments_hospital_uid'), 'departments', ['hospital_uid'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_uid'), 'departments', ['uid'], unique=False)
    op.create_table('hospital_ratings',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('hospital_uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=2, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_uid'], ['hospitals.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_hospital_ratings_hospital_uid'), 'hospital_ratings', ['hospital_uid'], unique=False)
    op.create_index(op.f('ix_hospital_ratings_user_uid'), 'hospital_ratings', ['user_uid'], unique=False)
    op.create_table('admins',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hospital_uid', sa.UUID(), nullable=True),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('admin_type', postgresql.ENUM('SUPER_ADMIN', 'HOSPITAL_ADMIN', 'DEPARTMENT_ADMIN', name='admin_type'), nullable=False),
    sa.Column('department_uid', sa.UUID(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['department_uid'], ['departments.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_uid'], ['hospitals.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_admins_department_uid'), 'admins', ['department_uid'], unique=False)
    op.create_index(op.f('ix_admins_hospital_uid'), 'admins', ['hospital_uid'], unique=False)
    op.create_index(op.f('ix_admins_user_uid'), 'admins', ['user_uid'], unique=False)
    op.create_table('doctors',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_of_residence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hospital_uid', sa.UUID(), nullable=True),
    sa.Column('department_uid', sa.UUID(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('UNDER_REVIEW', 'APPROVED', 'REJECTED', name='doctor_status'), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_uid'], ['departments.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_uid'], ['hospitals.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_doctors_department_uid'), 'doctors', ['department_uid'], unique=False)
    op.create_index(op.f('ix_doctors_hospital_uid'), 'doctors', ['hospital_uid'], unique=False)
    op.create_index(op.f('ix_doctors_user_uid'), 'doctors', ['user_uid'], unique=False)
    op.create_table('appointments',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('patient_uid', sa.UUID(), nullable=False),
    sa.Column('hospital_uid', sa.UUID(), nullable=False),
    sa.Column('appointment_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', 'IN_PROGRESS', 'RESCHEDULED', name='appointment_status'), nullable=False),
    sa.Column('doctor_uid', sa.UUID(), nullable=True),
    sa.Column('department_uid', sa.UUID(), nullable=False),
    sa.Column('rescheduled_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_uid'], ['departments.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_uid'], ['doctors.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_uid'], ['hospitals.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_uid'], ['patients.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_appointments_department_uid'), 'appointments', ['department_uid'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_uid'), 'appointments', ['doctor_uid'], unique=False)
    op.create_index(op.f('ix_appointments_hospital_uid'), 'appointments', ['hospital_uid'], unique=False)
    op.create_index(op.f('ix_appointments_patient_uid'), 'appointments', ['patient_uid'], unique=False)
    op.create_index(op.f('ix_appointments_uid'), 'appointments', ['uid'], unique=False)
    op.create_table('medical_records',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('patient_uid', sa.UUID(), nullable=False),
    sa.Column('doctor_uid', sa.UUID(), nullable=False),
    sa.Column('hospital_uid', sa.UUID(), nullable=True),
    sa.Column('record_type', postgresql.ENUM('DIAGNOSIS', 'LAB_RESULT', 'PRESCRIPTION', 'NOTE', name='record_type'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_uid'], ['doctors.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_uid'], ['hospitals.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_uid'], ['patients.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_medical_records_doctor_uid'), 'medical_records', ['doctor_uid'], unique=False)
    op.create_index(op.f('ix_medical_records_hospital_uid'), 'medical_records', ['hospital_uid'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_uid'), 'medical_records', ['patient_uid'], unique=False)
    op.create_index(op.f('ix_medical_records_uid'), 'medical_records', ['uid'], unique=False)
    op.create_table('medical_record_files',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('record_uid', sa.UUID(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_uid'], ['medical_records.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_medical_record_files_record_uid'), 'medical_record_files', ['record_uid'], unique=False)
    op.create_index(op.f('ix_medical_record_files_uid'), 'medical_record_files', ['uid'], unique=False)
    op.create_table('reschedulehistory',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('appointment_uid', sa.UUID(), nullable=False),
    sa.Column('old_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('rescheduled_by', sa.Uuid(), nullable=True),
    sa.Column('rescheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_uid'], ['appointments.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_reschedulehistory_appointment_uid'), 'reschedulehistory', ['appointment_uid'], unique=False)
    op.create_index(op.f('ix_reschedulehistory_uid'), 'reschedulehistory', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reschedulehistory_uid'), table_name='reschedulehistory')
    op.drop_index(op.f('ix_reschedulehistory_appointment_uid'), table_name='reschedulehistory')
    op.drop_table('reschedulehistory')
    op.drop_index(op.f('ix_medical_record_files_uid'), table_name='medical_record_files')
    op.drop_index(op.f('ix_medical_record_files_record_uid'), table_name='medical_record_files')
    op.drop_table('medical_record_files')
    op.drop_index(op.f('ix_medical_records_uid'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_patient_uid'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_hospital_uid'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_uid'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_appointments_uid'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_uid'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_hospital_uid'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_uid'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_department_uid'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctors_user_uid'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_uid'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_department_uid'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_admins_user_uid'), table_name='admins')
    op.drop_index(op.f('ix_admins_hospital_uid'), table_name='admins')
    op.drop_index(op.f('ix_admins_department_uid'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_hospital_ratings_user_uid'), table_name='hospital_ratings')
    op.drop_index(op.f('ix_hospital_ratings_hospital_uid'), table_name='hospital_ratings')
    op.drop_table('hospital_ratings')
    op.drop_index(op.f('ix_departments_uid'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_hospital_uid'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_refreshtokens_user_uid'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_uid'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_session_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_jti'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    op.drop_index(op.f('ix_patients_user_uid'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_user_uid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_uid'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_uid'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hospitals_user_uid'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signup_links_uid'), table_name='signup_links')
    op.drop_index(op.f('ix_signup_links_token'), table_name='signup_links')
    op.drop_table('signup_links')
    op.drop_index(op.f('ix_password_reset_tokens_uid'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_blacklistedtokens_session_id'), table_name='blacklistedtokens')
    op.drop_table('blacklistedtokens')
    # ### end Alembic commands ###
